import { Event, City } from './types'

export const events: Event[] = [
  // ── ATLANTA ──────────────────────────────────────────────
  {
    id: '1',
    slug: 'killer-mike-michael-atlanta-may-2026',
    city: 'atlanta',
    album: 'Michael',
    artist: 'Killer Mike',
    year: 2023,
    genre: 'Hip Hop / Rap',
    venue: 'Coffee Was Black Atlanta',
    address: '737 Ponce De Leon Ave NE',
    neighborhood: 'Poncey-Highland',
    date: '2026-05-22T18:00:00',
    doorsTime: '5:30 PM',
    startTime: '6:00 PM',
    price: 15,
    capacity: 20,
    spotsLeft: 20,
    description:
      "An Atlanta homecoming. Killer Mike's Michael is one of the most important rap albums of the decade — made right here, about right here. We'll listen front to back and let the city speak.",
    albumDescription:
      "Michael (2023) is Killer Mike's solo debut — a raw, honest, and spiritually charged record about Black manhood, Atlanta, and the weight of legacy. Named after his late father. It won the Grammy for Best Rap Album.",
    tags: ['Hip Hop', 'Atlanta', 'Grammy'],
    featured: true,
    cardBg: '#1A1A1A',
    cardAccent: '#C4922A',
    coverArt: '/covers/killer-mike-michael.jpg',
  },
  {
    id: '2',
    slug: 'kanye-college-dropout-atlanta-june-2026',
    city: 'atlanta',
    album: 'The College Dropout',
    artist: 'Kanye West',
    year: 2004,
    genre: 'Hip Hop',
    venue: 'Coffee Was Black Atlanta',
    address: '483 Edgewood Ave SE',
    neighborhood: 'Old Fourth Ward',
    date: '2026-06-05T18:00:00',
    doorsTime: '5:30 PM',
    startTime: '6:00 PM',
    price: 15,
    capacity: 20,
    spotsLeft: 20,
    description:
      "Before everything else, there was this. We're going back to the debut that changed rap — listening to The College Dropout the way it deserves: together, front to back, with no distractions.",
    albumDescription:
      "The College Dropout (2004) announced Kanye West as something entirely new in hip hop — soulful, funny, vulnerable, and ambitious all at once. Two decades later it still sounds like a statement.",
    tags: ['Hip Hop', 'Classic', 'Debut'],
    featured: true,
    cardBg: '#3D2B1A',
    cardAccent: '#D4A847',
    coverArt: '/covers/kanye-college-dropout.jpg',
  },
  {
    id: '3',
    slug: 'kanye-late-registration-atlanta-june-2026',
    city: 'atlanta',
    album: 'Late Registration',
    artist: 'Kanye West',
    year: 2005,
    genre: 'Hip Hop',
    venue: 'Coffee Was Black Atlanta',
    address: '675 Ponce De Leon Ave NE',
    neighborhood: 'Old Fourth Ward',
    date: '2026-06-19T18:00:00',
    doorsTime: '5:30 PM',
    startTime: '6:00 PM',
    price: 15,
    capacity: 20,
    spotsLeft: 20,
    description:
      "The follow-up that might have been even better than the debut. Jon Brion's orchestral arrangements, Kanye at his most ambitious. We'll sit with it and decide for ourselves.",
    albumDescription:
      "Late Registration (2005) is Kanye's sophomore record and one of the most lush, layered hip hop albums ever made. Co-produced with Jon Brion, it pushed the genre somewhere it had never been.",
    tags: ['Hip Hop', 'Classic', 'Orchestral'],
    featured: false,
    cardBg: '#2C1810',
    cardAccent: '#F2EBD9',
    coverArt: '/covers/kanye-late-registration.jpg',
  },
  {
    id: '4',
    slug: 'young-jeezy-thug-motivation-atlanta-july-2026',
    city: 'atlanta',
    album: "Let's Get It: Thug Motivation 101",
    artist: 'Young Jeezy',
    year: 2005,
    genre: 'Trap / Hip Hop',
    venue: 'Coffee Was Black Atlanta',
    address: '1402 Glenwood Ave SE',
    neighborhood: 'East Atlanta',
    date: '2026-07-03T18:00:00',
    doorsTime: '5:30 PM',
    startTime: '6:00 PM',
    price: 15,
    capacity: 20,
    spotsLeft: 20,
    description:
      "Trap music didn't start here, but it was born here. Young Jeezy's debut is an Atlanta document as much as it is an album. We're listening to it like that.",
    albumDescription:
      "Let's Get It: Thug Motivation 101 (2005) is the album that codified trap music and made Young Jeezy a street legend. Raw, cold, and undeniable — a product of Atlanta's streets at a specific moment in time.",
    tags: ['Trap', 'Atlanta', 'Classic'],
    featured: false,
    cardBg: '#0D1A0D',
    cardAccent: '#C4922A',
    coverArt: '/covers/young-jeezy-thug-motivation.jpg',
  },
  {
    id: '5',
    slug: 'stevie-wonder-songs-in-the-key-atlanta-july-2026',
    city: 'atlanta',
    album: 'Songs in the Key of Life',
    artist: 'Stevie Wonder',
    year: 1976,
    genre: 'Soul / R&B / Funk',
    venue: 'Coffee Was Black Atlanta',
    address: '737 Ponce De Leon Ave NE',
    neighborhood: 'Poncey-Highland',
    date: '2026-07-17T18:00:00',
    doorsTime: '5:30 PM',
    startTime: '6:00 PM',
    price: 15,
    capacity: 20,
    spotsLeft: 20,
    description:
      "A double album that requires the full treatment — two sides, no shortcuts. Songs in the Key of Life is one of the greatest albums ever made by any artist in any genre. Come ready.",
    albumDescription:
      "Songs in the Key of Life (1976) is Stevie Wonder's masterpiece — a sprawling, joyful, devastating double album that covers love, loss, politics, and everything in between. Prince said it was the album that made him want to make music.",
    tags: ['Soul', 'Classic', 'Double Album'],
    featured: true,
    cardBg: '#1E2D1E',
    cardAccent: '#D4A847',
    coverArt: '/covers/stevie-wonder-songs.jpg',
  },
  {
    id: '6',
    slug: 'frank-ocean-channel-orange-atlanta-july-2026',
    city: 'atlanta',
    album: 'channel ORANGE',
    artist: 'Frank Ocean',
    year: 2012,
    genre: 'R&B / Soul',
    venue: 'Coffee Was Black Atlanta',
    address: '2236 Martin Luther King Jr Way',
    neighborhood: 'North Oakland',
    date: '2026-07-31T18:00:00',
    doorsTime: '5:30 PM',
    startTime: '6:00 PM',
    price: 15,
    capacity: 20,
    spotsLeft: 20,
    description:
      "The debut that made everyone stop. channel ORANGE is a once-in-a-generation record — we'll listen to it in the dark and let it do what it does.",
    albumDescription:
      "channel ORANGE (2012) is Frank Ocean's debut album and one of the defining R&B records of the century so far. Loose, literary, and emotionally devastating — it sounds like nothing else before or since.",
    tags: ['R&B', 'Soul', 'Debut'],
    featured: true,
    cardBg: '#3D1A00',
    cardAccent: '#D4A847',
    coverArt: '/covers/frank-ocean-channel-orange.jpg',
  },
  {
    id: '7',
    slug: 'frank-ocean-blonde-atlanta-august-2026',
    city: 'atlanta',
    album: 'Blonde',
    artist: 'Frank Ocean',
    year: 2016,
    genre: 'R&B / Experimental',
    venue: 'Coffee Was Black Atlanta',
    address: '6080 Telegraph Ave',
    neighborhood: 'Temescal',
    date: '2026-08-14T18:00:00',
    doorsTime: '5:30 PM',
    startTime: '6:00 PM',
    price: 15,
    capacity: 20,
    spotsLeft: 20,
    description:
      "Four years of waiting and then this. Blonde rewards the kind of listening we practice here — slow, undistracted, and present. One of the few albums that genuinely improves with every listen.",
    albumDescription:
      "Blonde (2016) is Frank Ocean's second album and one of the most anticipated and celebrated records of its decade. Fragmented, intimate, and strangely timeless — it sounds like a private diary made public.",
    tags: ['R&B', 'Experimental', 'Intimate'],
    featured: true,
    cardBg: '#1A1A2E',
    cardAccent: '#C4922A',
    coverArt: '/covers/frank-ocean-blonde.jpg',
  },
  {
    id: '8',
    slug: 'kendrick-gkmc-atlanta-august-2026',
    city: 'atlanta',
    album: 'good kid, m.A.A.d city',
    artist: 'Kendrick Lamar',
    year: 2012,
    genre: 'Hip Hop',
    venue: 'Coffee Was Black Atlanta',
    address: '579 18th St',
    neighborhood: 'Uptown',
    date: '2026-08-28T18:00:00',
    doorsTime: '5:30 PM',
    startTime: '6:00 PM',
    price: 15,
    capacity: 20,
    spotsLeft: 20,
    description:
      "A short film on wax. Kendrick's major label debut is a narrative album that plays best in sequence, in a room, with people who are actually listening. That's exactly what we'll do.",
    albumDescription:
      "good kid, m.A.A.d city (2012) is Kendrick Lamar's major label debut — a cinematic concept album about growing up in Compton. It's the album that established him as the most important rapper of his generation.",
    tags: ['Hip Hop', 'Concept Album', 'West Coast'],
    featured: true,
    cardBg: '#1A0A2E',
    cardAccent: '#D4A847',
    coverArt: '/covers/kendrick-gkmc.jpg',
  },
  {
    id: '9',
    slug: 'badbadnotgood-sour-soul-atlanta-september-2026',
    city: 'atlanta',
    album: 'Sour Soul',
    artist: 'BADBADNOTGOOD & Ghostface Killah',
    year: 2015,
    genre: 'Jazz Hop',
    venue: 'Coffee Was Black Atlanta',
    address: '6080 Telegraph Ave',
    neighborhood: 'Temescal',
    date: '2026-09-11T18:00:00',
    doorsTime: '5:30 PM',
    startTime: '6:00 PM',
    price: 15,
    capacity: 20,
    spotsLeft: 20,
    description:
      "Jazz meets Wu-Tang in one of the most unexpected and perfect collaborations in recent memory. Sour Soul is a short, dense listen — we'll run it twice.",
    albumDescription:
      "Sour Soul (2015) pairs Toronto jazz trio BADBADNOTGOOD with Wu-Tang legend Ghostface Killah for a record that sounds like it could have come out of any decade. Cinematic, smoky, and completely its own thing.",
    tags: ['Jazz Hop', 'Collaboration', 'Wu-Tang'],
    featured: false,
    cardBg: '#2A1A0A',
    cardAccent: '#C4922A',
    coverArt: '/covers/badbadnotgood-sour-soul.jpg',
  },
  {
    id: '10',
    slug: 'protoje-a-matter-of-time-atlanta-september-2026',
    city: 'atlanta',
    album: 'A Matter of Time',
    artist: 'Protoje',
    year: 2018,
    genre: 'Reggae / Soul',
    venue: 'Coffee Was Black Atlanta',
    address: '2236 Martin Luther King Jr Way',
    neighborhood: 'North Oakland',
    date: '2026-09-25T18:00:00',
    doorsTime: '5:30 PM',
    startTime: '6:00 PM',
    price: 15,
    capacity: 20,
    spotsLeft: 20,
    description:
      "Protoje is one of the most important voices in contemporary reggae and Oakland has always known it. A Matter of Time is a record about patience, resistance, and joy — fitting for a room like this.",
    albumDescription:
      "A Matter of Time (2018) is Protoje's fourth studio album and his most fully realized — a blend of roots reggae, R&B, and soul that draws on classic Jamaican tradition while sounding entirely present. Features Wiz Khalifa and Chronixx.",
    tags: ['Reggae', 'Soul', 'Roots'],
    featured: false,
    cardBg: '#0A2A1A',
    cardAccent: '#D4A847',
    coverArt: '/covers/protoje-matter-of-time.jpg',
  },
]

export const cities: City[] = [
  {
    id: 'atlanta',
    name: 'Atlanta',
    state: 'GA',
    tagline: 'The South Has Something to Say',
    description:
      "Atlanta's listening party scene lives in the same neighborhoods that birthed the civil rights movement — Old Fourth Ward, West End, Poncey-Highland. We gather in bars and lounges where the music hits differently.",
    neighborhoods: 'Old Fourth Ward · Poncey-Highland · West End · Buckhead',
    upcomingCount: events.filter((e) => e.city === 'atlanta').length,
  },
  {
    id: 'oakland',
    name: 'Oakland',
    state: 'CA',
    tagline: "The Town Has Always Known",
    description:
      'Oakland has always run its own music — from the Black Arts Movement to funk and soul scenes that defined West Coast sound. We listen in the spots where the community already gathers.',
    neighborhoods: 'Temescal · Uptown · North Oakland · Fruitvale',
    upcomingCount: events.filter((e) => e.city === 'oakland').length,
  },
]

export const featuredEvents = events.filter((e) => e.featured).slice(0, 4)

export const getEventsByCity = (city: string) =>
  events.filter((e) => e.city === city)

export const getEventBySlug = (slug: string) =>
  events.find((e) => e.slug === slug) ?? null

export const getCityById = (id: string) =>
  cities.find((c) => c.id === id) ?? null

export function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-US', {
    weekday: 'long',
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  })
}

export function formatShortDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
  })
}
